### ISSUE TITLE
Undefined function log_exception

### ISSUE THREAD

**Issue by Nihilistik** [mikedfunk/CodeIgniter-Email-PHP-Errors#1]
I've trying to implement this addon but it doesn't work. Wherever i use the log_exception function, the undefined error pops up.

My codeigniter installation has the modules extension, can be found here:
https://bitbucket.org/wiredesignz/codeigniter-modular-extensions-hmvc
I dont know if its an error caused by the HMVC extension or because this addon only works with previous versions of CI.

I'm posting this here for anyone who has the same problem can share the solution or to warn future users about this issue.

**Comment by mikedfunk** [comment]
Sorry, this is for codeigniter 2.x. It will likely not work with the latest codeigniter 3.x. (assuming that's what you're using)

**Comment by kingkarki** [comment]
Any update on latest codeinigter?
